apiVersion: v1
kind: Secret
metadata:
  name: "nso-auth"
type: Opaque
data:
{{- if empty .Values.adminPassword }}
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "nso-auth") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $nso-auth to existing secret data or generate a random one when not exists
  {{- $nsoAuth := (get $secretData "adminPassword") | default (randAlphaNum 16 | b64enc) }}
  adminPassword: {{ $nsoAuth | quote }}
{{- else }}
  adminPassword: {{ .Values.adminPassword | b64enc }}
{{- end }}