apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "nso.fullname" . }}
    {{- if .Values.istio.enabled }}
    istio-injection: "enabled"
    {{- end }}
