{{- if .Values.istio.enabled }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  gateways:
    - istio-system/public
  hosts:
    - {{ .Values.fqdn }}
  http:
    - route:
        - destination:
            host: {{ include "nso.fullname" . }}
            port:
              number: 80
{{- end }}